openapi: 3.0.0
info:
  title: Controle de gastos
  description: API para gerenciar gastos pessoais
  version: 1.0.0
servers:
  - url: "http://localhost:3000/api/v1"
    description: Development server
paths:
  /usuarios:
    get:
      summary: Retorna todos os usuários
      parameters:
        - in: query
          name: nome
          schema:
            type: string
          description: Retorna os usuários que contém a string no nome
        - in: query
          name: offset
          schema:
            type: integer
          description: Quantidade de itens que será pulada
        - in: query
          name: limit
          schema:
            type: integer
          description: Quantidade de itens que será retornado
      responses:
        "200":
          description: Lista de usuários
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Usuario"
      tags:
        - usuarios
    post:
      summary: Cadastra um novo usuário
      requestBody:
        description: Usuário a ser cadastrado
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Usuario"

      responses:
        "200":
          description: Retorna o usuário cadastrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Usuario"
      tags:
        - usuarios
  "/usuarios/{id}":
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      summary: Retorna o usuário do id informado
      responses:
        "200":
          description: Usuário encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Usuario"
      tags:
        - usuarios
    put:
      summary: Atualiza o usuário do id informado
      requestBody:
        description: Usuário a ser atualizado
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Usuario"
      responses:
        "200":
          description: Retorna o usuário cadastrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Usuario"
      tags:
        - usuarios
    delete:
      summary: Remove o usuário do id informado
      responses:
        "200":
          description: Retorna o usuário removido
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Usuario"
      tags:
        - usuarios
  /usuarios/login:
    post:
      summary: Loga no sistema
      requestBody:
        description: Credenciais do usuário
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                senha:
                  type: string
                  writeOnly: true
              example:
                username: fmazzuco4
                senha: "1234"
              required:
                - username
                - senha
      responses:
        "200":
          description: Token de acesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                example:
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiNWRhNDgwNjVlNDM1YzYyNDcwODkwOWU5IiwiaWF0IjoxNTcxMTgzMjI4LCJleHAiOjE1NzExODY4Mjh9.w7w-2OlRMAkveOtdy_mecdPBHleIqGa6tJFABl-dKL0
      tags:
        - usuarios
  /contas:
    get:
      summary: Retorna todas as contas
      parameters:
        - in: query
          name: nome
          schema:
            type: string
          description: Retorna as contas que contém a string no nome
        - in: query
          name: offset
          schema:
            type: integer
          description: Quantidade de itens que será pulada
        - in: query
          name: limit
          schema:
            type: integer
          description: Quantidade de itens que será retornado
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista de contas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Conta"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      tags:
        - contas
    post:
      summary: Cadastra uma nova conta
      security:
        - bearerAuth: []
      requestBody:
        description: Conta a ser cadastrada
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Conta"
      responses:
        "200":
          description: Retorna a conta cadastrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Conta"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      tags:
        - contas
  "/contas/{id}":
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      summary: Retorna a conta do id informado
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Conta encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Conta"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      tags:
        - contas
    put:
      summary: Atualiza a conta do id informado
      security:
        - bearerAuth: []
      requestBody:
        description: Conta a ser atualizada
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Conta"
      responses:
        "200":
          description: Retorna a conta cadastrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Conta"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      tags:
        - contas
    delete:
      summary: Remove a conta do id informado
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Retorna a conta removida
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Conta"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      tags:
        - contas
  "/contas/{contaId}/lancamentos":
    parameters:
      - in: path
        name: contaId
        required: true
        schema:
          type: string
    get:
      summary: Retorna todos os lançamentos
      parameters:
        - in: query
          name: nome
          schema:
            type: string
          description: Retorna os lançamentos que contém a string no nome
        - in: query
          name: offset
          schema:
            type: integer
          description: Quantidade de itens que será pulada
        - in: query
          name: limit
          schema:
            type: integer
          description: Quantidade de itens que será retornado
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista de lançamentos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Lancamento"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      tags:
        - lancamentos
    post:
      summary: Cadastra um novo lançamento
      security:
        - bearerAuth: []
      requestBody:
        description: Lançamento a ser cadastrada
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Lancamento"
      responses:
        "200":
          description: Retorna o lancamento cadastrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Lancamento"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      tags:
        - lancamentos
  "/contas/{contaId}/lancamentos/{id}":
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - in: path
        name: contaId
        required: true
        schema:
          type: string
    get:
      summary: Retorna o lançamento do id informado
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lançamento encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Lancamento"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      tags:
        - lancamentos
    put:
      summary: Atualiza o lançamento do id informado
      security:
        - bearerAuth: []
      requestBody:
        description: Lançamento a ser atualizada
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Lancamento"
      responses:
        "200":
          description: Retorna o lançamento cadastrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Lancamento"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      tags:
        - lancamentos
    delete:
      summary: Remove a lançamento do id informado
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Retorna o lançamento removida
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Lancamento"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      tags:
        - lancamentos
  /etiquetas:
    get:
      summary: Retorna todas as etiquetas
      parameters:
        - in: query
          name: nome
          schema:
            type: string
          description: Retorna as etiquetas que contém a string no nome
        - in: query
          name: offset
          schema:
            type: integer
          description: Quantidade de itens que será pulada
        - in: query
          name: limit
          schema:
            type: integer
          description: Quantidade de itens que será retornado
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista de etiquetas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Etiqueta"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      tags:
        - etiquetas
    post:
      summary: Cadastra uma nova etiqueta
      security:
        - bearerAuth: []
      requestBody:
        description: Etiqueta a ser cadastrada
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Etiqueta"
      responses:
        "200":
          description: Retorna a etiqueta cadastrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Etiqueta"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      tags:
        - etiquetas
  "/etiquetas/{id}":
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      summary: Retorna a etiqueta do id informado
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Etiqueta encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Etiqueta"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      tags:
        - etiquetas
    put:
      summary: Atualiza a etiqueta do id informado
      security:
        - bearerAuth: []
      requestBody:
        description: Etiqueta a ser atualizada
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Etiqueta"
      responses:
        "200":
          description: Retorna a etiqueta cadastrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Etiqueta"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      tags:
        - etiquetas
    delete:
      summary: Remove a etiqueta do id informado
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Retorna a etiqueta removida
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Etiqueta"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      tags:
        - etiquetas
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        nome:
          type: string
        username:
          type: string
        senha:
          type: string
          writeOnly: true
      example:
        id: 5da268bab917a843a850531a
        nome: Francisco Mazzuco
        usuario: fmazzuco
        senha: "1234"
      required:
        - nome
        - username
        - senha
    Conta:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        nome:
          type: string
        usuario:
          $ref: "#/components/schemas/Usuario"
      example:
        id: 5da507f9f02e184328a07db2
        nome: Banco do Brasil
        usuario: 5da268bab917a843a850531a
      required:
        - nome
    Lancamento:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        nome:
          type: string
        conta:
          $ref: "#/components/schemas/Conta"
        usuario:
          $ref: "#/components/schemas/Usuario"
      example:
        id: 5da65a9ed96d201a60861bf9
        nome: Restaurante 123
        usuario: 5da268bab917a843a850531a
        conta: 5da507f9f02e184328a07db2
      required:
        - nome
    Etiqueta:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        nome:
          type: string
        usuario:
          $ref: "#/components/schemas/Usuario"
      example:
        id: 5da268bab917a843a850531a
        nome: Eletrônicos
        usuario: 5da268bab917a843a850531a
      required:
        - nome
  responses:
    UnauthorizedError:
      description: Unauthorized
tags:
  - name: usuarios
    description: Usuários
  - name: contas
    description: Contas
  - name: lancamentos
    description: Lançamentos
  - name: etiquetas
    description: Etiquetas
